#!/usr/bin/env bash
#
# gen-agents-md.sh — generate an AGENTS.md entry point so non-Claude coding
# agents (Codex, Cursor, Copilot, Gemini CLI, Windsurf, Zed, Jules, …) use the
# SOTA skills too.
#
# AGENTS.md is the cross-tool open standard (agents.md). The skill *content* is
# plain Markdown that any model reads; this just writes a thin pointer that tells
# the agent to route through the library and read rules on demand — it does NOT
# duplicate rule text. The index is built from each skill's SKILL.md frontmatter,
# so it stays in sync with the source.
#
# Idempotent: the SOTA section lives between managed markers, so re-running
# refreshes only that block and leaves the rest of your AGENTS.md untouched.
#
# Usage:
#   scripts/gen-agents-md.sh [--skills-dir DIR] [--output FILE] [--dry-run]
#
#   --skills-dir DIR   where the skills live (default: ~/.claude/skills if present,
#                      else the skills/ dir of this checkout)
#   --output FILE      AGENTS.md to write/update (default: ./AGENTS.md)
#
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd -- "$SCRIPT_DIR/.." && pwd)"
readonly BEGIN_MARK="<!-- >>> sota-skills (generated by gen-agents-md.sh — edits here are overwritten) >>> -->"
readonly END_MARK="<!-- <<< sota-skills <<< -->"

OUTPUT="AGENTS.md"
SKILLS_DIR=""
DRY_RUN=0

log()  { printf '  %s\n' "$*"; }
die()  { printf 'error: %s\n' "$*" >&2; exit 1; }
usage() { sed -n '2,/^set -euo/p' "$0" | sed 's/^# \{0,1\}//; /^set -euo/d'; exit "${1:-0}"; }

while [ $# -gt 0 ]; do
  case "$1" in
    --skills-dir) shift; [ $# -gt 0 ] || die "--skills-dir needs a path"; SKILLS_DIR="$1" ;;
    --output)     shift; [ $# -gt 0 ] || die "--output needs a path"; OUTPUT="$1" ;;
    --dry-run)    DRY_RUN=1 ;;
    -h|--help)    usage 0 ;;
    *)            die "unknown argument: $1 (try --help)" ;;
  esac
  shift
done

# --- resolve where the skills live -------------------------------------------
if [ -z "$SKILLS_DIR" ]; then
  if [ -d "$HOME/.claude/skills/sota" ]; then
    SKILLS_DIR="$HOME/.claude/skills"
  elif [ -d "$REPO/skills/sota" ]; then
    SKILLS_DIR="$REPO/skills"
  else
    die "could not find a skills dir — pass --skills-dir DIR"
  fi
fi
SKILLS_DIR="$(cd -- "$SKILLS_DIR" && pwd)"   # absolute
[ -d "$SKILLS_DIR/sota" ] || die "no sota/ under $SKILLS_DIR — is this a skills dir?"

# --- pull a one-line summary from a SKILL.md's frontmatter description --------
# Frontmatter is two fields (name + description); take the description's first
# sentence and squeeze whitespace.
skill_summary() {
  awk '
    BEGIN { infm=0; ind=0 }
    /^---[[:space:]]*$/ { infm++; next }
    infm==1 {
      if ($0 ~ /^description:/) { ind=1; sub(/^description:[[:space:]]*>?-?[[:space:]]*/, ""); }
      else if ($0 ~ /^[A-Za-z][A-Za-z0-9_-]*:/) { ind=0 }
      if (ind) { gsub(/^[[:space:]]+/, ""); buf = buf " " $0 }
    }
    END {
      sub(/^[[:space:]]+/, "", buf)
      # first sentence: up to the first ". "
      if (match(buf, /\. /)) buf = substr(buf, 1, RSTART)
      gsub(/[[:space:]]+/, " ", buf)
      print buf
    }
  ' "$1"
}

# --- build the managed block -------------------------------------------------
emit_block() {
  cat <<EOF
$BEGIN_MARK
## SOTA Engineering Skills

A state-of-the-art engineering skills library is available at \`$SKILLS_DIR\`.

**Always — every answer, not just code tasks:**

- **Validate before you assert.** Never state a claim about code, system state,
  configuration, installed versions, APIs, or external facts from memory. Verify
  it first against a primary source — read the file/code in full, run the command
  and read its output, or fetch the official docs at use time. Label anything
  unverified as such; never present it as fact. Applies to answers, proposals,
  and plans.
- **Keep docs current in the same change.** When you change code, behavior,
  config, or interfaces, update the affected docs (README, CHANGELOG, comments,
  runbooks, this AGENTS.md) in the same change, unprompted.

**For any task that builds, designs, refactors, debugs, reviews, or audits code**
— in any language — apply the library before acting, regardless of phrasing:

1. **Route**: read \`$SKILLS_DIR/sota/SKILL.md\` to map the task to the relevant
   domain and language skills.
2. **Load only what the task needs**: that skill's \`SKILL.md\`, then only the
   \`rules/*.md\` files matching the code in front of you. Never load everything.
3. **Modes**: BUILD applies the rules while writing; AUDIT reports findings as
   \`file:line | rule | severity | effort | fix\`.
4. **Stop and ask** on security-relevant decisions (authn/z, crypto, secrets,
   trust boundaries, network exposure) rather than silently picking; never trust
   training data for version/CVE/spec facts.
5. **Stack profile**: if one exists (e.g. \`~/.claude/profiles/*.md\`), treat its
   choices as the BUILD default and the AUDIT baseline.

### Skill index
EOF
  emit_one "$SKILLS_DIR/sota"          # router first — it is the entry point
  for d in "$SKILLS_DIR"/*/; do
    [ "$(basename "$d")" = sota ] && continue
    emit_one "$d"
  done
  printf '%s\n' "$END_MARK"
}

emit_one() {
  local d="${1%/}" name
  name="$(basename "$d")"
  [ -f "$d/SKILL.md" ] || return 0
  # shellcheck disable=SC2016  # backticks are literal Markdown code spans, not command substitution
  printf -- '- **%s** — %s (`%s/%s/SKILL.md`)\n' \
    "$name" "$(skill_summary "$d/SKILL.md")" "$SKILLS_DIR" "$name"
}

# --- assemble (create / replace-block / append) ------------------------------
# The block (with its markers) is written to a temp file so awk can splice it by
# line — passing multi-line text through `awk -v` is not portable.
block_file="$(mktemp)"
trap 'rm -f "$block_file"' EXIT
emit_block > "$block_file"

if [ "$DRY_RUN" -eq 1 ]; then
  cat "$block_file"
  exit 0
fi

if [ ! -f "$OUTPUT" ]; then
  cp "$block_file" "$OUTPUT"
elif grep -qF "$BEGIN_MARK" "$OUTPUT" && grep -qF "$END_MARK" "$OUTPUT"; then
  cp "$OUTPUT" "$OUTPUT.bak"
  awk -v b="$BEGIN_MARK" -v e="$END_MARK" -v f="$block_file" '
    index($0, b) { while ((getline line < f) > 0) print line; close(f); skip=1; next }
    index($0, e) { skip=0; next }
    skip!=1 { print }
  ' "$OUTPUT.bak" > "$OUTPUT"
else
  cp "$OUTPUT" "$OUTPUT.bak"
  { printf '\n'; cat "$block_file"; } >> "$OUTPUT"
fi

count="$(find "$SKILLS_DIR" -maxdepth 1 -mindepth 1 -type d | wc -l | tr -d ' ')"
log "wrote $OUTPUT — $count skills indexed, pointing at $SKILLS_DIR"
log "AGENTS.md is read by Codex, Cursor, Copilot, Gemini CLI, Windsurf, Zed, and more."
[ -f "$OUTPUT.bak" ] && log "previous version saved to $OUTPUT.bak"

cat <<'NEXT'

Notes:
  - Re-run after updating the library; only the managed block changes.
  - The index points at an absolute path. If you COMMIT this AGENTS.md to a
    shared repo, vendor the skills into the repo and re-run with
    --skills-dir ./path so teammates resolve it too.
NEXT
