#!/usr/bin/env bash
#
# gen-agents-md.sh — generate an AGENTS.md entry point so non-Claude coding
# agents (Codex, Cursor, Copilot, Gemini CLI, Windsurf, Zed, Jules, …) use the
# SOTA skills too.
#
# AGENTS.md is the cross-tool open standard (agents.md). The skill *content* is
# plain Markdown that any model reads; this just writes a thin pointer that tells
# the agent to route through the library and read rules on demand — it does NOT
# duplicate rule text. The index is built from each skill's SKILL.md frontmatter,
# so it stays in sync with the source.
#
# Idempotent: the SOTA section lives between managed markers, so re-running
# refreshes only that block and leaves the rest of your AGENTS.md untouched.
#
# Usage:
#   scripts/gen-agents-md.sh [--skills-dir DIR] [--output FILE] [--dry-run]
#                            [--siblings]
#
#   --skills-dir DIR   where the skills live (default: ~/.claude/skills if present,
#                      else the skills/ dir of this checkout)
#   --output FILE      AGENTS.md to write/update (default: ./AGENTS.md)
#   --siblings         also create a CLAUDE.md POINTER beside it, if and only if it
#                      does not already exist. It duplicates no byte: AGENTS.md stays
#                      the single source of truth.
#   --legacy-gemini    also handle GEMINI.md. Off by default: Antigravity CLI, which
#                      replaces Gemini CLI, reads AGENTS.md natively.
#
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd -- "$SCRIPT_DIR/.." && pwd)"
readonly BEGIN_MARK="<!-- >>> sota-skills (generated by gen-agents-md.sh — edits here are overwritten) >>> -->"
readonly END_MARK="<!-- <<< sota-skills <<< -->"

OUTPUT="AGENTS.md"
SKILLS_DIR=""
DRY_RUN=0
SIBLINGS=0
LEGACY_GEMINI=0

log()  { printf '  %s\n' "$*"; }
die()  { printf 'error: %s\n' "$*" >&2; exit 1; }
usage() { sed -n '2,/^set -euo/p' "$0" | sed 's/^# \{0,1\}//; /^set -euo/d'; exit "${1:-0}"; }

while [ $# -gt 0 ]; do
  case "$1" in
    --skills-dir) shift; [ $# -gt 0 ] || die "--skills-dir needs a path"; SKILLS_DIR="$1" ;;
    --output)     shift; [ $# -gt 0 ] || die "--output needs a path"; OUTPUT="$1" ;;
    --dry-run)    DRY_RUN=1 ;;
    --siblings)   SIBLINGS=1 ;;
    --legacy-gemini) LEGACY_GEMINI=1 ;;
    -h|--help)    usage 0 ;;
    *)            die "unknown argument: $1 (try --help)" ;;
  esac
  shift
done

# --- resolve where the skills live -------------------------------------------
if [ -z "$SKILLS_DIR" ]; then
  if [ -d "$HOME/.claude/skills/sota" ]; then
    SKILLS_DIR="$HOME/.claude/skills"
  elif [ -d "$REPO/skills/sota" ]; then
    SKILLS_DIR="$REPO/skills"
  else
    die "could not find a skills dir — pass --skills-dir DIR"
  fi
fi
SKILLS_DIR="$(cd -- "$SKILLS_DIR" && pwd)"   # absolute
[ -d "$SKILLS_DIR/sota" ] || die "no sota/ under $SKILLS_DIR — is this a skills dir?"

# --- pull a one-line summary from a SKILL.md's frontmatter description --------
# Frontmatter is two fields (name + description); take the description's first
# sentence and squeeze whitespace.
skill_summary() {
  awk '
    BEGIN { infm=0; ind=0 }
    /^---[[:space:]]*$/ { infm++; next }
    infm==1 {
      if ($0 ~ /^description:/) { ind=1; sub(/^description:[[:space:]]*>?-?[[:space:]]*/, ""); }
      else if ($0 ~ /^[A-Za-z][A-Za-z0-9_-]*:/) { ind=0 }
      if (ind) { gsub(/^[[:space:]]+/, ""); buf = buf " " $0 }
    }
    END {
      sub(/^[[:space:]]+/, "", buf)
      # first sentence: up to the first ". "
      if (match(buf, /\. /)) buf = substr(buf, 1, RSTART)
      gsub(/[[:space:]]+/, " ", buf)
      print buf
    }
  ' "$1"
}

# --- build the managed block -------------------------------------------------
emit_block() {
  cat <<EOF
$BEGIN_MARK
## SOTA Engineering Skills

A state-of-the-art engineering skills library is available at \`$SKILLS_DIR\`.

**Always — every answer, not just code tasks:**

- **Validate before you assert.** Never state a claim about code, system state,
  configuration, installed versions, APIs, or external facts from memory. Verify
  it first against a primary source — read the file/code in full, run the command
  and read its output, or fetch the official docs at use time. Label anything
  unverified as such; never present it as fact. Applies to answers, proposals,
  and plans.
- **Keep docs current in the same change.** When you change code, behavior,
  config, or interfaces, update the affected docs (README, CHANGELOG, comments,
  runbooks, this AGENTS.md) in the same change, unprompted.

**For any task that builds, designs, refactors, debugs, reviews, or audits code**
— in any language — apply the library before acting, regardless of phrasing:

1. **Route**: read \`$SKILLS_DIR/sota/SKILL.md\` to map the task to the relevant
   domain and language skills.
2. **Load only what the task needs**: that skill's \`SKILL.md\`, then only the
   \`rules/*.md\` files matching the code in front of you. Never load everything.
3. **Modes**: BUILD applies the rules while writing; AUDIT reports findings as
   \`file:line | rule | severity | effort | fix\`.
4. **Stop and ask** on security-relevant decisions (authn/z, crypto, secrets,
   trust boundaries, network exposure) rather than silently picking; never trust
   training data for version/CVE/spec facts.
5. **Stack profile**: if one exists (e.g. \`~/.claude/profiles/*.md\`), treat its
   choices as the BUILD default and the AUDIT baseline.

### Skill index
EOF
  emit_one "$SKILLS_DIR/sota"          # router first — it is the entry point
  for d in "$SKILLS_DIR"/*/; do
    [ "$(basename "$d")" = sota ] && continue
    emit_one "$d"
  done
  printf '%s\n' "$END_MARK"
}

emit_one() {
  local d="${1%/}" name
  name="$(basename "$d")"
  [ -f "$d/SKILL.md" ] || return 0
  # shellcheck disable=SC2016  # backticks are literal Markdown code spans, not command substitution
  printf -- '- **%s** — %s (`%s/%s/SKILL.md`)\n' \
    "$name" "$(skill_summary "$d/SKILL.md")" "$SKILLS_DIR" "$name"
}

# --- assemble (create / replace-block / append) ------------------------------
# The block (with its markers) is written to a temp file so awk can splice it by
# line — passing multi-line text through `awk -v` is not portable.
block_file="$(mktemp)"
trap 'rm -f "$block_file"' EXIT
emit_block > "$block_file"

if [ "$DRY_RUN" -eq 1 ]; then
  cat "$block_file"
  exit 0
fi

if [ ! -f "$OUTPUT" ]; then
  cp "$block_file" "$OUTPUT"
elif grep -qxF "$BEGIN_MARK" "$OUTPUT" && grep -qxF "$END_MARK" "$OUTPUT"; then
  # Exact-whole-line detection (-x) matching the awk $0== below: a line that
  # merely QUOTES a marker (docs, code fence) must not trigger a splice.
  cp "$OUTPUT" "$OUTPUT.bak"
  awk -v b="$BEGIN_MARK" -v e="$END_MARK" -v f="$block_file" '
    $0 == b { while ((getline line < f) > 0) print line; close(f); skip=1; next }
    $0 == e { skip=0; next }
    skip!=1 { print }
  ' "$OUTPUT.bak" > "$OUTPUT"
elif grep -qF "$BEGIN_MARK" "$OUTPUT" || grep -qF "$END_MARK" "$OUTPUT"; then
  # A lone/altered marker: appending would duplicate the block, and the NEXT
  # run's splice would then eat user content between orphan and copy — refuse.
  die "$OUTPUT has a sota-skills marker that is unpaired or altered — restore the exact marker lines (or delete the block), then re-run"
else
  cp "$OUTPUT" "$OUTPUT.bak"
  { printf '\n'; cat "$block_file"; } >> "$OUTPUT"
fi

# --- sibling entry points: report always, create only on request ------------
#
# Claude Code reads CLAUDE.md, Gemini CLI reads GEMINI.md; neither reads
# AGENTS.md by default. So a repo carrying only AGENTS.md leaves both reading
# NOTHING, which presents as the model getting worse rather than as a missing
# file. Neither sibling gets a COPY: AGENTS.md stays the single source of truth.
#
#   CLAUDE.md -> `@AGENTS.md`     (code.claude.com/docs/en/memory, AGENTS.md section;
#                                  that page recommends it OVER a symlink, and notes a
#                                  symlink on Windows needs Administrator/Developer Mode)
#   GEMINI.md -> `@./AGENTS.md`   LEGACY ONLY -- see below. Gemini CLI does support the
#                                  import (docs/cli/gemini-md.md, reference/memport.md;
#                                  its examples are all `./`-prefixed).
# Both processors ignore `@` inside code spans/fences, so a backticked path is inert.
#
# GEMINI.md IS NOT THE DEFAULT ANY MORE, and this is measured rather than read:
# Gemini CLI is being retired in favour of ANTIGRAVITY CLI, which stopped serving
# free/Pro/Ultra individuals on 2026-06-18. Verified on this machine 2026-09-10:
# `gemini -p ...` on 0.59.0 exits with
#   IneligibleTierError: This client is no longer supported for Gemini Code Assist
#   for individuals ... migrate to the Antigravity suite
# and Antigravity's own bundled docs (antigravity-cli/builtin/skills/agy-customizations/
# docs/rules.md) say it discovers "Directory-Based Rules (`GEMINI.md` / `AGENTS.md`)" --
# so the successor reads AGENTS.md NATIVELY and needs no pointer at all. GEMINI.md is
# therefore reported as OPTIONAL/legacy (paid-API and enterprise users still on the old
# CLI), never as something missing.
#
# CORRECTED 2026-09-10: an earlier draft of this block asserted Gemini CLI had no
# import directive and gave it prose instead. That was WRONG -- the claim rested on
# two docs that happen not to mention it, and `docs/reference/memport.md` is a whole
# page about it. An absence needs a second method with a different failure mode; two
# shallow reads of the same doc set is not that.
#
# NEVER OVERWRITE, and never silently accept either. An existing file is somebody's
# content -- clobbering it would delete the instructions this is meant to deliver --
# but a file that never mentions AGENTS.md is a file that does not work with this
# library, so it is reported as ACTION NEEDED with the exact line to add.
sibling_report() {  # <path> <import-line> <tool> <verify-cmd>
  local f="$1" line="$2" tool="$3" verify="$4" base
  base="$(basename -- "$OUTPUT")"

  if [ ! -e "$f" ] && [ ! -L "$f" ]; then
    if [ "$SIBLINGS" -eq 1 ]; then
      printf '%s\n' "$line" > "$f"
      log "created $f — pointer only ($line), no duplicated content"
    else
      log "MISSING  $f — $tool reads it, not $base. Add a file containing: $line"
      log "         (or re-run with --siblings to have it written for you)"
    fi
    return 0
  fi

  # It exists. Decide whether it already reaches AGENTS.md, and never write.
  if [ -L "$f" ]; then
    if [ -e "$f" ]; then
      log "ok       $f is a symlink and resolves — leaving it alone"
    else
      log "ACTION   $f is a DANGLING symlink — $tool reads nothing. Repoint it at $base"
    fi
    return 0
  fi

  # The core.symlinks=false / Windows checkout: a plain file whose entire content
  # is the link text. It looks like a pointer and instructs nothing.
  if [ "$(tr -d '[:space:]' < "$f")" = "$base" ]; then
    log "ACTION   $f contains only the bare text '$base' — that is a symlink checked out"
    log "         as a plain file (core.symlinks=false, or Windows without Developer Mode)."
    log "         $tool reads it as literal text and follows nothing. Replace with: $line"
    return 0
  fi

  if grep -qF -- "$base" "$f"; then
    log "ok       $f already references $base — leaving it alone"
  else
    log "ACTION   $f exists and never mentions $base, so $tool will not see the SOTA"
    log "         routing block. NOT modified. Add this as its FIRST line:  $line"
  fi
  log "         verify what actually loaded: $verify"
}

sib_dir="$(dirname -- "$OUTPUT")"
sib_base="$(basename -- "$OUTPUT")"
sibling_report "$sib_dir/CLAUDE.md" "@$sib_base"   "Claude Code" "/context (under Memory files)"
if [ "$LEGACY_GEMINI" -eq 1 ]; then
  sibling_report "$sib_dir/GEMINI.md" "@./$sib_base" "Gemini CLI (legacy)" "/memory show"
else
  log "skipped   GEMINI.md — Antigravity CLI (Gemini CLI's successor) reads $sib_base"
  log "          natively, so no pointer is needed. Pass --legacy-gemini if you are an"
  log "          enterprise/paid-API user still on the old Gemini CLI."
fi

# -L: the default layout symlinks skill dirs (install.sh), which plain -type d
# would not count — a successful run used to report "0 skills indexed".
count="$(find -L "$SKILLS_DIR" -maxdepth 1 -mindepth 1 -type d | wc -l | tr -d ' ')"
log "wrote $OUTPUT — $count skills indexed, pointing at $SKILLS_DIR"
log "AGENTS.md is read by Codex, Cursor, Copilot, Gemini CLI, Windsurf, Zed, and more."
[ -f "$OUTPUT.bak" ] && log "previous version saved to $OUTPUT.bak"

cat <<'NEXT'

Notes:
  - Re-run after updating the library; only the managed block changes.
  - The index points at an absolute path. If you COMMIT this AGENTS.md to a
    shared repo, vendor the skills into the repo and re-run with
    --skills-dir ./path so teammates resolve it too.
NEXT
